### ISSUE TITLE
React Integration

### ISSUE THREAD

**Issue by mihar-22** [vidstack/elements#78]
## Tasks

- [ ] Complete #79.
- [ ] Create `createReactCustomElementType`.
- [ ] Automatically generate wrappers via `custom-elements.json` or TypeScript parser and output in `react` directory.
- [ ] Automatically generate SSR friendly wrappers via similar method and output in `react/ssr` directory.
- [ ] Add stories for each React component.
- [ ] Add Conditional Export to `package.json` for react.
- [ ] Add basic React SSR and Next.js examples in `examples` directory.
- [ ] Run integration tests on new examples.

## References

- https://github.com/vidstack/player/blob/main/docs/architecture/overview.md#framework-integrations

**Comment by AntonOfTheWoods** [comment]
It looks like React 18 might (possibly) have somewhat better support for custom elements https://github.com/facebook/react/pull/22184. That probably doesn't affect `vds-elements` plans? 

Waiting for "native" support, would one of the approaches mentioned here be a good temporary measure? https://css-tricks.com/3-approaches-to-integrate-react-with-custom-elements/. Given the components, any suggestions on which might be a better temporary approach?

**Comment by mihar-22** [comment]
Housekeeping, closing outdated issue. Sorry @AntonOfTheWoods I somehow missed your message, and yes with the upcoming React 18 release adding support for custom elements, we will be reviewing how we can approach this problem without framework wrappers.
